import type {
  Agent,
  CurrentUser,
  Employee,
  EntityRef,
  Lead,
  Project,
  Task,
  Ticket,
  Todo,
} from '@/types/domain'

export const id = (prefix: string, n: number) => `${prefix}_${n.toString().padStart(3, '0')}`

export const nowOffset = (minutes: number) => new Date(Date.now() + minutes * 60_000).toISOString()

export const USER: CurrentUser = {
  id: id('emp', 1),
  name: 'Maya Chen',
  email: 'maya@northline.studio',
  role: 'Founder',
  workspace: 'Northline Studio',
}

const emp = (n: number, name: string, role: string): EntityRef => ({
  type: 'employee',
  id: id('emp', n),
  label: name,
  subtitle: role,
})

export const agentRef = (n: number, name: string, status?: string): EntityRef => ({
  type: 'agent',
  id: id('agt', n),
  label: name,
  status,
})

const client = (n: number, name: string, status?: string): EntityRef => ({
  type: 'client',
  id: id('cli', n),
  label: name,
  status,
})

const projectRef = (n: number, name: string): EntityRef => ({
  type: 'project',
  id: id('prj', n),
  label: name,
})

export const MAYA = emp(1, 'Maya Chen', 'Founder')
export const JORDAN = emp(2, 'Jordan Hale', 'Account Director')
export const PRIYA = emp(3, 'Priya Shah', 'Delivery Lead')
export const ELI = emp(4, 'Eli Park', 'Design')
export const SAM = emp(5, 'Sam Okonkwo', 'Engineering')

export const NORTHSTAR = client(1, 'Northstar Logistics', 'strategic')
export const HELIOS = client(2, 'Helios Health', 'growth')
export const MERIDIAN = client(3, 'Meridian Retail', 'growth')
export const ATLAS = client(4, 'Atlas Fintech', 'past')

export function createEmployees(): Employee[] {
  return [
    {
      id: MAYA.id,
      name: 'Maya Chen',
      role: 'Founder / operator',
      availability: 'available',
      availability_note: null,
      active_task_count: 4,
      blocked_task_count: 1,
      workload: 'balanced',
      workload_reason: 'Four active items, one waiting on a human decision.',
      coverage: ['Northstar Logistics', 'Agency operations'],
      initials: 'MC',
    },
    {
      id: JORDAN.id,
      name: 'Jordan Hale',
      role: 'Account Director',
      availability: 'busy',
      availability_note: 'In client workshop until 16:30 local.',
      active_task_count: 6,
      blocked_task_count: 2,
      workload: 'over_capacity',
      workload_reason: 'Six active account items plus two blockers. Backend marks this as over capacity.',
      coverage: ['Helios Health', 'Atlas Fintech', 'Vesper Hotels lead'],
      initials: 'JH',
    },
    {
      id: PRIYA.id,
      name: 'Priya Shah',
      role: 'Delivery Lead',
      availability: 'available',
      availability_note: null,
      active_task_count: 3,
      blocked_task_count: 1,
      workload: 'heavy',
      workload_reason: 'Helios scope review is blocking the milestone; other work is on track.',
      coverage: ['Helios Health Website', 'Meridian Retail'],
      initials: 'PS',
    },
    {
      id: ELI.id,
      name: 'Eli Park',
      role: 'Design',
      availability: 'available',
      availability_note: null,
      active_task_count: 2,
      blocked_task_count: 0,
      workload: 'balanced',
      workload_reason: 'Two design tickets in review, no blockers.',
      coverage: ['Helios Health Website'],
      initials: 'EP',
    },
    {
      id: SAM.id,
      name: 'Sam Okonkwo',
      role: 'Engineering',
      availability: 'away',
      availability_note: 'Unavailable until Monday 09:00 local. Discord mapped.',
      active_task_count: 1,
      blocked_task_count: 1,
      workload: 'light',
      workload_reason: 'One blocked API investigation pending vendor logs.',
      coverage: ['Northstar Customer Portal'],
      initials: 'SO',
    },
  ]
}

export function createAgents(): Agent[] {
  return [
    {
      id: id('agt', 1),
      name: 'CEO Agent',
      purpose: 'Operations briefing, risk synthesis, and founder decision support.',
      kind: 'ceo',
      status: 'available',
      health_reason: 'Heartbeat 42s ago. Last briefing completed successfully.',
      heartbeat_at: nowOffset(-0.7),
      current_action: null,
      last_action: 'Generated today’s operations briefing',
      queue_depth: 0,
      permitted_tools: ['read_workspace', 'draft_briefing', 'ask_followup'],
      escalation_owner_id: MAYA.id,
      related_employee_id: null,
      related_client_id: null,
    },
    {
      id: id('agt', 2),
      name: 'Support Agent',
      purpose: 'Telegram intake, draft replies, and SLA watch for client desk.',
      kind: 'support',
      status: 'busy',
      health_reason: 'Heartbeat 11s ago. Currently drafting a reply; not merely a recent successful run.',
      heartbeat_at: nowOffset(-0.18),
      current_action: 'Drafting support reply for Northstar ticket NS-184',
      last_action: 'Classified Helios ticket HH-91 as escalation',
      queue_depth: 3,
      permitted_tools: ['read_ticket', 'draft_reply', 'request_approval', 'tag_ticket'],
      escalation_owner_id: MAYA.id,
      related_employee_id: null,
      related_client_id: null,
    },
    {
      id: id('agt', 3),
      name: 'Northstar Account Agent',
      purpose: 'Dedicated account coverage for Northstar Logistics.',
      kind: 'account',
      status: 'awaiting_approval',
      health_reason: 'Heartbeat 1m ago. A drafted client reply is waiting on human approval.',
      heartbeat_at: nowOffset(-1),
      current_action: 'Waiting for approval to send NS-184 reply',
      last_action: 'Summarized API latency thread',
      queue_depth: 1,
      permitted_tools: ['read_client', 'draft_reply', 'create_task', 'request_approval'],
      escalation_owner_id: MAYA.id,
      related_employee_id: null,
      related_client_id: NORTHSTAR.id,
    },
    {
      id: id('agt', 4),
      name: 'Helios Account Agent',
      purpose: 'Dedicated account coverage for Helios Health.',
      kind: 'account',
      status: 'available',
      health_reason: 'Heartbeat 38s ago. Idle, no queued work.',
      heartbeat_at: nowOffset(-0.6),
      current_action: null,
      last_action: 'Flagged unscoped homepage revision #4',
      queue_depth: 0,
      permitted_tools: ['read_client', 'create_task', 'draft_update'],
      escalation_owner_id: JORDAN.id,
      related_employee_id: null,
      related_client_id: HELIOS.id,
    },
    {
      id: id('agt', 5),
      name: 'Meridian Account Agent',
      purpose: 'Dedicated account coverage for Meridian Retail.',
      kind: 'account',
      status: 'degraded',
      health_reason: 'Heartbeat missing for 12m. Last CRM write failed on a required field.',
      heartbeat_at: nowOffset(-12),
      current_action: null,
      last_action: 'Failed to update Meridian ticket MR-44',
      queue_depth: 2,
      permitted_tools: ['read_client', 'draft_reply', 'update_crm'],
      escalation_owner_id: PRIYA.id,
      related_employee_id: null,
      related_client_id: MERIDIAN.id,
    },
    {
      id: id('agt', 6),
      name: 'Jordan Subagent',
      purpose: 'Discord employee subagent for Jordan Hale.',
      kind: 'employee_subagent',
      status: 'available',
      health_reason: 'Heartbeat 20s ago via Discord identity map.',
      heartbeat_at: nowOffset(-0.33),
      current_action: null,
      last_action: 'Reminded Jordan of Vesper Hotels follow-up',
      queue_depth: 1,
      permitted_tools: ['read_assigned_work', 'nudge', 'draft_update'],
      escalation_owner_id: JORDAN.id,
      related_employee_id: JORDAN.id,
      related_client_id: null,
    },
    {
      id: id('agt', 7),
      name: 'Priya Subagent',
      purpose: 'Discord employee subagent for Priya Shah.',
      kind: 'employee_subagent',
      status: 'busy',
      health_reason: 'Heartbeat 9s ago. Collecting Helios milestone evidence.',
      heartbeat_at: nowOffset(-0.15),
      current_action: 'Collecting Helios milestone evidence',
      last_action: 'Logged blocker on homepage revision',
      queue_depth: 1,
      permitted_tools: ['read_assigned_work', 'log_blocker', 'draft_status'],
      escalation_owner_id: PRIYA.id,
      related_employee_id: PRIYA.id,
      related_client_id: null,
    },
  ]
}

export function createProjects(): Project[] {
  return [
    {
      id: id('prj', 1),
      name: 'Northstar Customer Portal',
      client: NORTHSTAR,
      health: 'needs_attention',
      health_reason: 'API latency incident is open on NS-184 and the engineering owner is away until Monday.',
      phase: 'Stabilization',
      completion_label: '18 of 24 tasks complete · 1 overdue',
      tasks_done: 18,
      tasks_total: 24,
      next_milestone: 'Latency hotfix in staging',
      next_milestone_at: nowOffset(36 * 60),
      owner: MAYA,
      overdue_count: 1,
      latest_blocker: 'Waiting on vendor logs; Sam is away.',
      objective: 'Restore portal p95 latency under 400ms and keep the client informed.',
      latest_outcome: 'Support draft prepared; not sent.',
      team: [MAYA, SAM, agentRef(3, 'Northstar Account Agent')],
      latest_report_excerpt: 'Latency remains above SLO. Client is calm if a dated plan is sent today.',
      version: 11,
    },
    {
      id: id('prj', 2),
      name: 'Helios Health Website Revamp',
      client: HELIOS,
      health: 'at_risk',
      health_reason: 'Homepage revision #4 is outside signed scope. Delivery is blocked until a founder decision on change-order vs absorb.',
      phase: 'Build',
      completion_label: '22 of 41 tasks complete · 3 overdue',
      tasks_done: 22,
      tasks_total: 41,
      next_milestone: 'Content freeze',
      next_milestone_at: nowOffset(-8 * 60),
      owner: PRIYA,
      overdue_count: 3,
      latest_blocker: 'Unscoped homepage revision #4. Waiting on Maya.',
      objective: 'Launch the public site without absorbing unpaid scope.',
      latest_outcome: 'Design exploration complete; legal pages still with client.',
      team: [PRIYA, ELI, JORDAN, agentRef(4, 'Helios Account Agent')],
      latest_report_excerpt: 'Scope/revision creep is the delivery risk, not craft quality.',
      version: 19,
    },
    {
      id: id('prj', 3),
      name: 'Meridian Retail Campaign Ops',
      client: MERIDIAN,
      health: 'on_track',
      health_reason: 'Milestone work is on schedule. Tracking-pixel ticket is waiting on the customer, not the team.',
      phase: 'Run',
      completion_label: '9 of 12 tasks complete · 0 overdue',
      tasks_done: 9,
      tasks_total: 12,
      next_milestone: 'Weekly ops handoff',
      next_milestone_at: nowOffset(20 * 60),
      owner: PRIYA,
      overdue_count: 0,
      latest_blocker: null,
      objective: 'Keep campaign ops running with a clear customer-owned tracking setup.',
      latest_outcome: 'Internal checklist complete; pixel values requested from client.',
      team: [PRIYA, agentRef(5, 'Meridian Account Agent')],
      latest_report_excerpt: 'On track. Do not chase internally while the client holds the pixel IDs.',
      version: 7,
    },
    {
      id: id('prj', 4),
      name: 'Atlas Fintech Retain',
      client: ATLAS,
      health: 'at_risk',
      health_reason: 'No meaningful client activity in 12 days and a pause request is sitting in the desk. Churn risk is explicit.',
      phase: 'Retain',
      completion_label: '4 of 8 tasks complete · 2 overdue',
      tasks_done: 4,
      tasks_total: 8,
      next_milestone: 'Retention conversation',
      next_milestone_at: nowOffset(24 * 60),
      owner: JORDAN,
      overdue_count: 2,
      latest_blocker: 'Pause request AT-12 has no owner decision.',
      objective: 'Confirm whether Atlas continues, pauses, or churns — do not let this stay implicit.',
      latest_outcome: 'Last QBR sent; no reply.',
      team: [JORDAN, MAYA],
      latest_report_excerpt: 'Churn signal is the unseen one: silence plus a pause ticket.',
      version: 5,
    },
  ]
}

export function createTasks(): Task[] {
  return [
    {
      id: id('tsk', 1),
      title: 'Decide Helios homepage revision #4',
      description: 'Client requested a fourth homepage direction after sign-off. This is outside the statement of work.',
      acceptance_criteria: [
        'Maya records absorb vs change-order',
        'Priya is unblocked to schedule content freeze',
        'Client is told the decision in writing',
      ],
      project: projectRef(2, 'Helios Health Website Revamp'),
      client: HELIOS,
      owner: MAYA,
      assignee: MAYA,
      assignee_kind: 'human',
      status: 'blocked',
      priority: 'urgent',
      due_at: nowOffset(-6 * 60),
      latest_activity_at: nowOffset(-40),
      latest_activity: 'Helios Account Agent flagged unscoped revision.',
      blocker_reason: 'Waiting on founder decision: absorb the revision or issue a change order.',
      waiting_on: MAYA,
      linked_ticket_id: id('tkt', 2),
      linked_lead_id: null,
      linked_run_ids: [id('run', 4)],
      created_by_agent: true,
      version: 6,
    },
    {
      id: id('tsk', 2),
      title: 'Send dated latency plan to Northstar',
      description: 'Client asked when portal latency will be under SLO. Draft exists; it has not been sent.',
      acceptance_criteria: ['Draft approved', 'Telegram delivery confirmed', 'Task marked done only after sent'],
      project: projectRef(1, 'Northstar Customer Portal'),
      client: NORTHSTAR,
      owner: MAYA,
      assignee: agentRef(3, 'Northstar Account Agent'),
      assignee_kind: 'agent',
      status: 'in_review',
      priority: 'high',
      due_at: nowOffset(2 * 60),
      latest_activity_at: nowOffset(-8),
      latest_activity: 'Support Agent drafted a reply. Awaiting approval.',
      blocker_reason: null,
      waiting_on: MAYA,
      linked_ticket_id: id('tkt', 1),
      linked_lead_id: null,
      linked_run_ids: [id('run', 1)],
      created_by_agent: true,
      version: 4,
    },
    {
      id: id('tsk', 3),
      title: 'Follow up Vesper Hotels proposal',
      description: 'Proposal sent five days ago. No next step is logged.',
      acceptance_criteria: ['Next conversation booked or lost reason captured'],
      project: projectRef(2, 'Helios Health Website Revamp'),
      client: HELIOS,
      owner: JORDAN,
      assignee: JORDAN,
      assignee_kind: 'human',
      status: 'blocked',
      priority: 'high',
      due_at: nowOffset(-2 * 24 * 60),
      latest_activity_at: nowOffset(-5 * 24 * 60),
      latest_activity: 'Proposal emailed. No follow-up logged.',
      blocker_reason: 'Waiting on Jordan to send the follow-up; next step is overdue.',
      waiting_on: JORDAN,
      linked_ticket_id: null,
      linked_lead_id: id('led', 1),
      linked_run_ids: [id('run', 6)],
      created_by_agent: false,
      version: 3,
    },
    {
      id: id('tsk', 4),
      title: 'Collect vendor logs for NS portal',
      description: 'Need origin logs from the CDN vendor to confirm the latency source.',
      acceptance_criteria: ['Logs attached', 'Sam reviews on Monday'],
      project: projectRef(1, 'Northstar Customer Portal'),
      client: NORTHSTAR,
      owner: SAM,
      assignee: SAM,
      assignee_kind: 'human',
      status: 'blocked',
      priority: 'high',
      due_at: nowOffset(18 * 60),
      latest_activity_at: nowOffset(-3 * 60),
      latest_activity: 'Vendor asked for a ticket ID. Sam is away.',
      blocker_reason: 'Engineering owner unavailable until Monday.',
      waiting_on: SAM,
      linked_ticket_id: id('tkt', 1),
      linked_lead_id: null,
      linked_run_ids: [],
      created_by_agent: false,
      version: 2,
    },
    {
      id: id('tsk', 5),
      title: 'Legal pages copy for Helios',
      description: 'Privacy and terms still with client legal.',
      acceptance_criteria: ['Client legal signs off', 'Pages in CMS'],
      project: projectRef(2, 'Helios Health Website Revamp'),
      client: HELIOS,
      owner: PRIYA,
      assignee: PRIYA,
      assignee_kind: 'human',
      status: 'blocked',
      priority: 'medium',
      due_at: nowOffset(12 * 60),
      latest_activity_at: nowOffset(-26 * 60),
      latest_activity: 'Nudged client legal yesterday.',
      blocker_reason: 'Waiting on client legal review.',
      waiting_on: HELIOS,
      linked_ticket_id: null,
      linked_lead_id: null,
      linked_run_ids: [],
      created_by_agent: false,
      version: 5,
    },
    {
      id: id('tsk', 6),
      title: 'Install Meridian tracking pixels',
      description: 'Cannot complete until client sends pixel IDs.',
      acceptance_criteria: ['Pixel IDs received', 'QA screenshot attached'],
      project: projectRef(3, 'Meridian Retail Campaign Ops'),
      client: MERIDIAN,
      owner: PRIYA,
      assignee: agentRef(5, 'Meridian Account Agent'),
      assignee_kind: 'agent',
      status: 'in_progress',
      priority: 'medium',
      due_at: nowOffset(30 * 60),
      latest_activity_at: nowOffset(-90),
      latest_activity: 'Asked client for pixel IDs. CRM update failed.',
      blocker_reason: null,
      waiting_on: MERIDIAN,
      linked_ticket_id: id('tkt', 3),
      linked_lead_id: null,
      linked_run_ids: [id('run', 3)],
      created_by_agent: true,
      version: 8,
    },
    {
      id: id('tsk', 7),
      title: 'Atlas retention conversation',
      description: 'Pause request plus 12 days of silence. Needs a human conversation, not another automated nudge.',
      acceptance_criteria: ['Jordan or Maya speaks with Atlas', 'Continue / pause / churn recorded'],
      project: projectRef(4, 'Atlas Fintech Retain'),
      client: ATLAS,
      owner: JORDAN,
      assignee: JORDAN,
      assignee_kind: 'human',
      status: 'ready',
      priority: 'urgent',
      due_at: nowOffset(8 * 60),
      latest_activity_at: nowOffset(-12 * 24 * 60),
      latest_activity: 'QBR sent. No reply.',
      blocker_reason: null,
      waiting_on: null,
      linked_ticket_id: id('tkt', 5),
      linked_lead_id: null,
      linked_run_ids: [],
      created_by_agent: false,
      version: 2,
    },
    {
      id: id('tsk', 8),
      title: 'Helios component QA pass',
      description: 'Design QA on inner pages.',
      acceptance_criteria: ['QA checklist complete', 'Bugs filed'],
      project: projectRef(2, 'Helios Health Website Revamp'),
      client: HELIOS,
      owner: ELI,
      assignee: ELI,
      assignee_kind: 'human',
      status: 'in_progress',
      priority: 'medium',
      due_at: nowOffset(10 * 60),
      latest_activity_at: nowOffset(-50),
      latest_activity: 'Started inner-page QA.',
      blocker_reason: null,
      waiting_on: null,
      linked_ticket_id: null,
      linked_lead_id: null,
      linked_run_ids: [],
      created_by_agent: false,
      version: 1,
    },
  ]
}

export function createTodos(): Todo[] {
  return [
    {
      id: id('tdo', 1),
      title: 'Approve Northstar latency reply before send',
      group: 'needs_my_action',
      completed: false,
      priority: 'urgent',
      owner: MAYA,
      assignee: MAYA,
      assignee_kind: 'human',
      client: NORTHSTAR,
      project: projectRef(1, 'Northstar Customer Portal'),
      due_at: nowOffset(2 * 60 + 15),
      rationale: 'Generated reply is not a sent reply. SLA is still open.',
      blocker_reason: null,
      agent_owned: false,
      completable: false,
      task_id: id('tsk', 2),
      version: 1,
    },
    {
      id: id('tdo', 2),
      title: 'Call the Helios scope decision',
      group: 'needs_my_action',
      completed: false,
      priority: 'urgent',
      owner: MAYA,
      assignee: MAYA,
      assignee_kind: 'human',
      client: HELIOS,
      project: projectRef(2, 'Helios Health Website Revamp'),
      due_at: nowOffset(-6 * 60),
      rationale: 'Revision creep is blocking content freeze.',
      blocker_reason: 'Waiting on founder absorb vs change-order.',
      agent_owned: false,
      completable: true,
      task_id: id('tsk', 1),
      version: 1,
    },
    {
      id: id('tdo', 3),
      title: 'Review CEO briefing exceptions',
      group: 'today',
      completed: false,
      priority: 'high',
      owner: MAYA,
      assignee: MAYA,
      assignee_kind: 'human',
      client: null,
      project: null,
      due_at: nowOffset(4 * 60),
      rationale: 'Daily ritual so exceptions do not wait for a meeting.',
      blocker_reason: null,
      agent_owned: false,
      completable: true,
      task_id: null,
      version: 1,
    },
    {
      id: id('tdo', 4),
      title: 'Draft weekly Helios status for legal audience',
      group: 'delegated',
      completed: false,
      priority: 'medium',
      owner: PRIYA,
      assignee: agentRef(7, 'Priya Subagent'),
      assignee_kind: 'agent',
      client: HELIOS,
      project: projectRef(2, 'Helios Health Website Revamp'),
      due_at: nowOffset(9 * 60),
      rationale: 'Agent is collecting evidence. Work is not complete.',
      blocker_reason: null,
      agent_owned: true,
      completable: false,
      task_id: id('tsk', 5),
      version: 1,
    },
    {
      id: id('tdo', 5),
      title: 'Receive Meridian pixel IDs',
      group: 'waiting_on_client',
      completed: false,
      priority: 'medium',
      owner: PRIYA,
      assignee: agentRef(5, 'Meridian Account Agent'),
      assignee_kind: 'agent',
      client: MERIDIAN,
      project: projectRef(3, 'Meridian Retail Campaign Ops'),
      due_at: nowOffset(30 * 60),
      rationale: 'Cannot install pixels without client IDs.',
      blocker_reason: 'Waiting on customer.',
      agent_owned: true,
      completable: false,
      task_id: id('tsk', 6),
      version: 1,
    },
    {
      id: id('tdo', 6),
      title: 'Prep Atlas retention talking points',
      group: 'later',
      completed: false,
      priority: 'high',
      owner: JORDAN,
      assignee: JORDAN,
      assignee_kind: 'human',
      client: ATLAS,
      project: projectRef(4, 'Atlas Fintech Retain'),
      due_at: nowOffset(26 * 60),
      rationale: 'Needed before the retention conversation.',
      blocker_reason: null,
      agent_owned: false,
      completable: true,
      task_id: id('tsk', 7),
      version: 1,
    },
  ]
}

export function createLeads(): Lead[] {
  return [
    {
      id: id('led', 1),
      organization: 'Vesper Hotels',
      contact_name: 'Amelia Ruiz',
      contact_role: 'CMO',
      service_fit: 'Brand site + booking ops',
      stage: 'proposal',
      owner: JORDAN,
      source: 'Referral — Helios',
      next_step: 'Follow up on sent proposal',
      next_step_at: nowOffset(-5 * 24 * 60),
      last_activity_at: nowOffset(-5 * 24 * 60),
      health_reasons: ['Proposal sent without follow-up', 'Next step overdue'],
      deal_value: 84000,
      qualification: {
        budget: 'Confirmed band $70–90k',
        timeline: 'Launch before winter season',
        decision_maker: 'Amelia Ruiz',
        next_step: 'Follow up on sent proposal',
      },
      notes: 'Warm referral. Amelia asked for a quieter visual system than their current site.',
      linked_client_id: null,
      linked_project_id: null,
      version: 4,
    },
    {
      id: id('led', 2),
      organization: 'Brightline Schools',
      contact_name: 'Noah Adeyemi',
      contact_role: 'Director of Comms',
      service_fit: 'District microsites',
      stage: 'discovery',
      owner: null,
      source: 'Inbound web',
      next_step: 'Assign owner and book discovery',
      next_step_at: nowOffset(-2 * 24 * 60),
      last_activity_at: nowOffset(-3 * 24 * 60),
      health_reasons: ['No owner', 'Next step overdue'],
      deal_value: 36000,
      qualification: {
        budget: 'Unknown',
        timeline: 'Fall enrollment cycle',
        decision_maker: null,
        next_step: 'Assign owner and book discovery',
      },
      notes: 'Public-sector procurement likely. Do not advance to proposal without an owner.',
      linked_client_id: null,
      linked_project_id: null,
      version: 2,
    },
    {
      id: id('led', 3),
      organization: 'Oak & Iron',
      contact_name: 'Claire Dent',
      contact_role: 'Founder',
      service_fit: 'DTC relaunch',
      stage: 'qualified',
      owner: JORDAN,
      source: 'Telegram',
      next_step: 'Await product photos from Claire',
      next_step_at: nowOffset(2 * 24 * 60),
      last_activity_at: nowOffset(-18 * 60),
      health_reasons: ['Awaiting client reply'],
      deal_value: 28000,
      qualification: {
        budget: 'Confirmed $25–30k',
        timeline: 'Q4 catalog drop',
        decision_maker: 'Claire Dent',
        next_step: 'Await product photos from Claire',
      },
      notes: 'Fit is strong. Waiting on assets, not a sales stall.',
      linked_client_id: null,
      linked_project_id: null,
      version: 3,
    },
    {
      id: id('led', 4),
      organization: 'Lumen Pay',
      contact_name: 'Chris Lang',
      contact_role: 'COO',
      service_fit: 'Fintech marketing site',
      stage: 'new',
      owner: MAYA,
      source: 'Conference',
      next_step: null,
      next_step_at: null,
      last_activity_at: nowOffset(-6 * 60),
      health_reasons: ['Missing qualification data', 'No next step'],
      deal_value: null,
      qualification: {
        budget: null,
        timeline: null,
        decision_maker: 'Chris Lang',
        next_step: null,
      },
      notes: 'Met at a booth. Do not mark qualified until budget and timeline exist.',
      linked_client_id: null,
      linked_project_id: null,
      version: 1,
    },
    {
      id: id('led', 5),
      organization: 'Harbor Clinic',
      contact_name: 'Dr. Lina Cho',
      contact_role: 'Managing partner',
      service_fit: 'Clinic sites + patient intake',
      stage: 'negotiation',
      owner: MAYA,
      source: 'Helios intro',
      next_step: 'Redline MSA on Friday call',
      next_step_at: nowOffset(22 * 60),
      last_activity_at: nowOffset(-8 * 60),
      health_reasons: [],
      deal_value: 52000,
      qualification: {
        budget: 'Confirmed $50k',
        timeline: 'January go-live',
        decision_maker: 'Dr. Lina Cho',
        next_step: 'Redline MSA on Friday call',
      },
      notes: 'Healthy. Legal is the remaining gate, not interest.',
      linked_client_id: null,
      linked_project_id: null,
      version: 6,
    },
    {
      id: id('led', 6),
      organization: 'Kinetic Apparel',
      contact_name: 'Omar Singh',
      contact_role: 'Head of Brand',
      service_fit: 'Campaign microsite',
      stage: 'nurture',
      owner: JORDAN,
      source: 'Outbound',
      next_step: 'Check in next quarter',
      next_step_at: nowOffset(40 * 24 * 60),
      last_activity_at: nowOffset(-14 * 24 * 60),
      health_reasons: ['No activity after qualification'],
      deal_value: 18000,
      qualification: {
        budget: 'Paused internally',
        timeline: 'Unknown',
        decision_maker: 'Omar Singh',
        next_step: 'Check in next quarter',
      },
      notes: 'Budget freeze. Keep in nurture; do not force a proposal.',
      linked_client_id: null,
      linked_project_id: null,
      version: 2,
    },
  ]
}

export function createTickets(): Ticket[] {
  return [
    {
      id: id('tkt', 1),
      number: 'NS-184',
      subject: 'Portal API latency above SLO',
      client: NORTHSTAR,
      contact_name: 'Ravi Menon',
      priority: 'urgent',
      sla_deadline_at: nowOffset(2 * 60 + 15),
      sla_reason: 'Strategic client, priority incident. First response SLA is 4 hours from Telegram intake.',
      assignee: MAYA,
      assignee_kind: 'human',
      latest_preview: 'Draft ready: dated plan for staging hotfix. Not sent.',
      updated_at: nowOffset(-8),
      tags: ['incident', 'portal', 'vip'],
      queues: ['mine', 'vip', 'sla_risk', 'awaiting_internal'],
      status: 'open',
      dedicated_agent: agentRef(3, 'Northstar Account Agent', 'awaiting_approval'),
      draft: {
        id: id('msg', 14),
        ticket_id: id('tkt', 1),
        speaker: 'agent',
        speaker_name: 'Support Agent',
        body: 'Ravi — we have isolated the latency to the origin cache, not the app servers. Staging hotfix is scheduled for Monday 09:00 local with Sam. We will post a checkpoint as soon as vendor logs land. This is a draft and has not been sent.',
        created_at: nowOffset(-8),
        delivery_state: 'awaiting_approval',
        delivery_at: null,
        delivery_id: null,
        approved_by: null,
        channel: 'telegram',
      },
      messages: [
        {
          id: id('msg', 11),
          ticket_id: id('tkt', 1),
          speaker: 'client',
          speaker_name: 'Ravi Menon',
          body: 'Portal search is taking 8–12s this morning. Shippers are complaining. When will this be under the SLO?',
          created_at: nowOffset(-3 * 60 + 20),
          delivery_state: 'sent',
          delivery_at: nowOffset(-3 * 60 + 20),
          delivery_id: 'tg_184_1',
          approved_by: null,
          channel: 'telegram',
        },
        {
          id: id('msg', 12),
          ticket_id: id('tkt', 1),
          speaker: 'system',
          speaker_name: 'System',
          body: 'Support Agent accepted intake from Telegram and opened NS-184. SLA clock started.',
          created_at: nowOffset(-3 * 60 + 19),
          delivery_state: 'sent',
          delivery_at: nowOffset(-3 * 60 + 19),
          delivery_id: null,
          approved_by: null,
          channel: 'internal',
        },
        {
          id: id('msg', 13),
          ticket_id: id('tkt', 1),
          speaker: 'human',
          speaker_name: 'Maya Chen',
          body: 'Internal: Sam is away. Do not promise a same-day prod ship. Draft a dated staging plan.',
          created_at: nowOffset(-50),
          delivery_state: 'sent',
          delivery_at: nowOffset(-50),
          delivery_id: null,
          approved_by: null,
          channel: 'internal',
        },
      ],
      version: 9,
    },
    {
      id: id('tkt', 2),
      number: 'HH-91',
      subject: 'Homepage revision #4 after sign-off',
      client: HELIOS,
      contact_name: 'Naomi Wells',
      priority: 'high',
      sla_deadline_at: nowOffset(-40),
      sla_reason: 'Escalated commercial dispute. First-response SLA already breached.',
      assignee: JORDAN,
      assignee_kind: 'human',
      latest_preview: 'Client: “We assumed unlimited homepage directions.”',
      updated_at: nowOffset(-35),
      tags: ['scope', 'escalated'],
      queues: ['escalated', 'awaiting_internal', 'sla_risk'],
      status: 'escalated',
      dedicated_agent: agentRef(4, 'Helios Account Agent'),
      draft: null,
      messages: [
        {
          id: id('msg', 21),
          ticket_id: id('tkt', 2),
          speaker: 'client',
          speaker_name: 'Naomi Wells',
          body: 'We assumed unlimited homepage directions were included. Revision 4 is a must before freeze.',
          created_at: nowOffset(-6 * 60),
          delivery_state: 'sent',
          delivery_at: nowOffset(-6 * 60),
          delivery_id: 'tg_91_1',
          approved_by: null,
          channel: 'telegram',
        },
        {
          id: id('msg', 22),
          ticket_id: id('tkt', 2),
          speaker: 'agent',
          speaker_name: 'Helios Account Agent',
          body: 'Logged as out-of-scope versus signed SOW. Escalated to Maya. No client-facing reply has been sent.',
          created_at: nowOffset(-40),
          delivery_state: 'sent',
          delivery_at: nowOffset(-40),
          delivery_id: null,
          approved_by: null,
          channel: 'internal',
        },
      ],
      version: 4,
    },
    {
      id: id('tkt', 3),
      number: 'MR-44',
      subject: 'Need tracking pixel IDs',
      client: MERIDIAN,
      contact_name: 'Jess Cole',
      priority: 'medium',
      sla_deadline_at: nowOffset(18 * 60),
      sla_reason: 'Standard response SLA. Clock paused in spirit while awaiting customer; server still tracks deadline.',
      assignee: PRIYA,
      assignee_kind: 'human',
      latest_preview: 'Asked client for pixel IDs. Delivery of that ask succeeded.',
      updated_at: nowOffset(-90),
      tags: ['tracking'],
      queues: ['awaiting_customer'],
      status: 'pending',
      dedicated_agent: agentRef(5, 'Meridian Account Agent', 'degraded'),
      draft: null,
      messages: [
        {
          id: id('msg', 31),
          ticket_id: id('tkt', 3),
          speaker: 'human',
          speaker_name: 'Priya Shah',
          body: 'Jess, we are ready to install. Please send the Meta and Google pixel IDs when you have them.',
          created_at: nowOffset(-90),
          delivery_state: 'sent',
          delivery_at: nowOffset(-90),
          delivery_id: 'tg_44_2',
          approved_by: PRIYA,
          channel: 'telegram',
        },
      ],
      version: 3,
    },
    {
      id: id('tkt', 4),
      number: 'NS-190',
      subject: 'Invoice coding question',
      client: NORTHSTAR,
      contact_name: 'Ravi Menon',
      priority: 'low',
      sla_deadline_at: nowOffset(10 * 60),
      sla_reason: 'Billing question, 12h first response.',
      assignee: MAYA,
      assignee_kind: 'human',
      latest_preview: 'Which PO should March retainers hit?',
      updated_at: nowOffset(-70),
      tags: ['billing'],
      queues: ['mine', 'vip'],
      status: 'open',
      dedicated_agent: agentRef(3, 'Northstar Account Agent'),
      draft: null,
      messages: [
        {
          id: id('msg', 41),
          ticket_id: id('tkt', 4),
          speaker: 'client',
          speaker_name: 'Ravi Menon',
          body: 'Which PO should the March retainer hit? Finance is asking.',
          created_at: nowOffset(-70),
          delivery_state: 'sent',
          delivery_at: nowOffset(-70),
          delivery_id: 'tg_190_1',
          approved_by: null,
          channel: 'telegram',
        },
      ],
      version: 1,
    },
    {
      id: id('tkt', 5),
      number: 'AT-12',
      subject: 'Request to pause retainers',
      client: ATLAS,
      contact_name: 'Kenji Mori',
      priority: 'high',
      sla_deadline_at: nowOffset(5 * 60),
      sla_reason: 'Churn-risk conversation. Do not auto-reply with a pause confirmation.',
      assignee: null,
      assignee_kind: 'unassigned',
      latest_preview: 'We may need to pause for a quarter.',
      updated_at: nowOffset(-4 * 60),
      tags: ['churn', 'retain'],
      queues: ['unassigned', 'sla_risk'],
      status: 'open',
      dedicated_agent: null,
      draft: null,
      messages: [
        {
          id: id('msg', 51),
          ticket_id: id('tkt', 5),
          speaker: 'client',
          speaker_name: 'Kenji Mori',
          body: 'We may need to pause the retainer for a quarter while we reset the product org.',
          created_at: nowOffset(-4 * 60),
          delivery_state: 'sent',
          delivery_at: nowOffset(-4 * 60),
          delivery_id: 'tg_12_1',
          approved_by: null,
          channel: 'telegram',
        },
      ],
      version: 1,
    },
    {
      id: id('tkt', 6),
      number: 'HH-77',
      subject: 'CMS training recording',
      client: HELIOS,
      contact_name: 'Naomi Wells',
      priority: 'low',
      sla_deadline_at: nowOffset(-2 * 24 * 60),
      sla_reason: 'Resolved after training recording was delivered.',
      assignee: ELI,
      assignee_kind: 'human',
      latest_preview: 'Recording delivered.',
      updated_at: nowOffset(-2 * 24 * 60),
      tags: ['training'],
      queues: ['resolved'],
      status: 'resolved',
      dedicated_agent: agentRef(4, 'Helios Account Agent'),
      draft: null,
      messages: [
        {
          id: id('msg', 61),
          ticket_id: id('tkt', 6),
          speaker: 'human',
          speaker_name: 'Eli Park',
          body: 'Naomi — training recording is in the shared folder. Closing this out.',
          created_at: nowOffset(-2 * 24 * 60),
          delivery_state: 'sent',
          delivery_at: nowOffset(-2 * 24 * 60),
          delivery_id: 'tg_77_9',
          approved_by: ELI,
          channel: 'telegram',
        },
      ],
      version: 2,
    },
  ]
}
