import type { AgentRun, Approval, NotificationItem, Report } from '@/types/domain'
import { ATLAS, ELI, HELIOS, id, JORDAN, MAYA, nowOffset, PRIYA } from './seed'

export function createApprovals(): Approval[] {
  return [
    {
      id: id('apr', 1),
      action_label: 'Send Telegram reply on NS-184',
      effect: 'Delivers the drafted latency plan to Ravi Menon on Telegram. Does not change production systems.',
      related: { type: 'ticket', id: id('tkt', 1), label: 'NS-184 Portal API latency' },
      requester: { type: 'agent', id: id('agt', 2), label: 'Support Agent' },
      requested_at: nowOffset(-8),
      expires_at: nowOffset(50),
      rationale: 'External send. A generated reply is not a sent reply until you approve.',
      status: 'requested',
      decided_by: null,
      decided_at: null,
      conflict_reason: null,
      version: 1,
    },
    {
      id: id('apr', 2),
      action_label: 'Issue Helios change order for homepage revision #4',
      effect: 'Creates a commercial change order and unblocks Priya. Does not send the client email until a later approval.',
      related: { type: 'task', id: id('tsk', 1), label: 'Decide Helios homepage revision #4' },
      requester: { type: 'agent', id: id('agt', 4), label: 'Helios Account Agent' },
      requested_at: nowOffset(-40),
      expires_at: nowOffset(8 * 60),
      rationale: 'Consequential commercial action. Needs founder approval.',
      status: 'requested',
      decided_by: null,
      decided_at: null,
      conflict_reason: null,
      version: 1,
    },
    {
      id: id('apr', 3),
      action_label: 'Retry Meridian CRM write',
      effect: 'Retries the failed CRM field update. Does not message the client.',
      related: { type: 'agent_run', id: id('run', 3), label: 'Meridian CRM update' },
      requester: { type: 'agent', id: id('agt', 5), label: 'Meridian Account Agent' },
      requested_at: nowOffset(-3 * 24 * 60),
      expires_at: nowOffset(-2 * 24 * 60),
      rationale: 'Retry window expired.',
      status: 'expired',
      decided_by: null,
      decided_at: null,
      conflict_reason: null,
      version: 2,
    },
    {
      id: id('apr', 4),
      action_label: 'Send Helios training recording',
      effect: 'Telegram delivery of CMS training link.',
      related: { type: 'ticket', id: id('tkt', 6), label: 'HH-77 CMS training recording' },
      requester: ELI,
      requested_at: nowOffset(-3 * 24 * 60),
      expires_at: nowOffset(-2 * 24 * 60),
      rationale: 'External send completed.',
      status: 'executed',
      decided_by: ELI,
      decided_at: nowOffset(-2 * 24 * 60),
      conflict_reason: null,
      version: 3,
    },
  ]
}

export function createRuns(): AgentRun[] {
  return [
    {
      id: id('run', 1),
      agent: { type: 'agent', id: id('agt', 2), label: 'Support Agent' },
      goal: 'Draft a dated latency plan for Northstar ticket NS-184 without sending it.',
      action_label: 'Drafted support reply',
      related: { type: 'ticket', id: id('tkt', 1), label: 'NS-184' },
      status: 'awaiting_approval',
      started_at: nowOffset(-18),
      ended_at: null,
      duration_ms: 10 * 60 * 1000,
      trigger: 'Telegram intake + SLA watch',
      initiator: { type: 'agent', id: id('agt', 2), label: 'Support Agent' },
      model_version: 'support-reply.v4',
      cost_tokens: 4120,
      approval_state: 'requested',
      outcome_summary: 'Draft ready. Waiting on Maya. Nothing has been sent to the client.',
      inputs_summary: 'Ticket thread, SLO policy, Sam’s unavailability, staging window. No secrets included.',
      actions: [
        { label: 'Read ticket NS-184', result: 'Loaded 3 messages and SLA clock.' },
        {
          label: 'Draft Telegram reply',
          result: 'Created an unsent draft.',
          entity: { type: 'ticket', id: id('tkt', 1), label: 'NS-184 draft' },
        },
        {
          label: 'Request send approval',
          result: 'Approval apr_001 opened.',
          entity: { type: 'approval', id: id('apr', 1), label: 'Send NS-184 reply' },
        },
      ],
      outputs: [
        {
          label: 'Unsent Telegram draft',
          body: 'Dated staging hotfix Monday 09:00 local. Explicitly not sent.',
        },
      ],
      events: [
        {
          id: 'ev1',
          at: nowOffset(-18),
          title: 'Run queued',
          detail: 'SLA watch requested a draft, not a send.',
          kind: 'system',
        },
        {
          id: 'ev2',
          at: nowOffset(-16),
          title: 'Read client thread',
          detail: 'Sanitized ticket context loaded.',
          kind: 'action',
        },
        {
          id: 'ev3',
          at: nowOffset(-10),
          title: 'Drafted support reply',
          detail: 'Reply stored as draft / awaiting approval.',
          kind: 'result',
        },
        {
          id: 'ev4',
          at: nowOffset(-8),
          title: 'Approval requested',
          detail: 'Maya must approve before Telegram delivery.',
          kind: 'approval',
        },
      ],
      related_records: [
        { type: 'ticket', id: id('tkt', 1), label: 'NS-184' },
        { type: 'task', id: id('tsk', 2), label: 'Send dated latency plan' },
        { type: 'approval', id: id('apr', 1), label: 'Send Telegram reply' },
        { type: 'project', id: id('prj', 1), label: 'Northstar Customer Portal' },
      ],
      failure: null,
      version: 4,
    },
    {
      id: id('run', 2),
      agent: { type: 'agent', id: id('agt', 1), label: 'CEO Agent' },
      goal: 'Produce the live operations briefing for Maya.',
      action_label: 'Generated operations briefing',
      related: { type: 'report', id: id('rpt', 1), label: 'Daily operations brief' },
      status: 'succeeded',
      started_at: nowOffset(-25),
      ended_at: nowOffset(-22),
      duration_ms: 3 * 60 * 1000,
      trigger: 'Scheduled briefing',
      initiator: { type: 'agent', id: id('agt', 1), label: 'CEO Agent' },
      model_version: 'ceo-brief.v2',
      cost_tokens: 8800,
      approval_state: 'none',
      outcome_summary: 'Briefing ready with two human decisions and one SLA risk.',
      inputs_summary: 'Open tickets, tasks, leads, capacity, recent runs. Workspace scoped.',
      actions: [
        { label: 'Aggregate exceptions', result: 'Built command-center payload.' },
        {
          label: 'Write report revision',
          result: 'Created daily operations brief r3.',
          entity: { type: 'report', id: id('rpt', 1), label: 'Daily operations brief' },
        },
      ],
      outputs: [{ label: 'Briefing summary', body: 'Attention: two decisions, one SLA risk, Helios scope creep.' }],
      events: [
        { id: 'e1', at: nowOffset(-25), title: 'Queued', detail: 'Scheduled slot.', kind: 'system' },
        { id: 'e2', at: nowOffset(-23), title: 'Read live queues', detail: 'Exceptions aggregated.', kind: 'action' },
        { id: 'e3', at: nowOffset(-22), title: 'Briefing ready', detail: 'Report revision 3 stored.', kind: 'result' },
      ],
      related_records: [{ type: 'report', id: id('rpt', 1), label: 'Daily operations brief' }],
      failure: null,
      version: 3,
    },
    {
      id: id('run', 3),
      agent: { type: 'agent', id: id('agt', 5), label: 'Meridian Account Agent' },
      goal: 'Update CRM that Meridian pixel ticket is waiting on the customer.',
      action_label: 'CRM update failed',
      related: { type: 'ticket', id: id('tkt', 3), label: 'MR-44' },
      status: 'failed',
      started_at: nowOffset(-95),
      ended_at: nowOffset(-93),
      duration_ms: 2 * 60 * 1000,
      trigger: 'Ticket state change',
      initiator: { type: 'agent', id: id('agt', 5), label: 'Meridian Account Agent' },
      model_version: 'account-sync.v1',
      cost_tokens: 640,
      approval_state: 'none',
      outcome_summary: 'CRM rejected the write: required field next_touch_at was empty.',
      inputs_summary: 'Ticket MR-44 status, assignee, waiting-on-customer flag.',
      actions: [{ label: 'Write CRM field', result: 'Rejected by CRM validation.' }],
      outputs: [],
      events: [
        { id: 'f1', at: nowOffset(-95), title: 'Started', detail: 'CRM sync after customer wait.', kind: 'system' },
        {
          id: 'f2',
          at: nowOffset(-93),
          title: 'CRM validation error',
          detail: 'next_touch_at required. No client message sent.',
          kind: 'error',
        },
      ],
      related_records: [
        { type: 'ticket', id: id('tkt', 3), label: 'MR-44' },
        { type: 'task', id: id('tsk', 6), label: 'Install Meridian tracking pixels' },
      ],
      failure: {
        summary: 'CRM rejected the update because next_touch_at was missing. Safe to retry after a date is set.',
        retry_eligible: true,
        correlation_id: 'corr_md_44_19',
      },
      version: 2,
    },
    {
      id: id('run', 4),
      agent: { type: 'agent', id: id('agt', 4), label: 'Helios Account Agent' },
      goal: 'Determine whether homepage revision #4 is in scope.',
      action_label: 'Flagged unscoped revision',
      related: { type: 'task', id: id('tsk', 1), label: 'Helios revision decision' },
      status: 'succeeded',
      started_at: nowOffset(-55),
      ended_at: nowOffset(-41),
      duration_ms: 14 * 60 * 1000,
      trigger: 'New Helios ticket HH-91',
      initiator: { type: 'agent', id: id('agt', 4), label: 'Helios Account Agent' },
      model_version: 'account-scope.v3',
      cost_tokens: 5100,
      approval_state: 'requested',
      outcome_summary: 'Out of signed scope. Change-order approval opened. No client email sent.',
      inputs_summary: 'Signed SOW excerpt, ticket HH-91, prior homepage sign-off. No contract files dumped raw.',
      actions: [
        { label: 'Compare to SOW', result: 'Revision 4 not listed.' },
        {
          label: 'Create blocked task',
          result: 'Task tsk_001 opened.',
          entity: { type: 'task', id: id('tsk', 1), label: 'Decide Helios homepage revision #4' },
        },
      ],
      outputs: [{ label: 'Scope finding', body: 'Revision #4 is outside signed homepage count.' }],
      events: [
        { id: 'h1', at: nowOffset(-55), title: 'Started', detail: 'Scope check.', kind: 'system' },
        { id: 'h2', at: nowOffset(-48), title: 'Read SOW fields', detail: 'Homepage directions: 3 included.', kind: 'action' },
        { id: 'h3', at: nowOffset(-41), title: 'Escalated', detail: 'Approval requested from Maya.', kind: 'approval' },
      ],
      related_records: [
        { type: 'ticket', id: id('tkt', 2), label: 'HH-91' },
        { type: 'task', id: id('tsk', 1), label: 'Helios revision decision' },
        { type: 'approval', id: id('apr', 2), label: 'Issue change order' },
      ],
      failure: null,
      version: 5,
    },
    {
      id: id('run', 5),
      agent: { type: 'agent', id: id('agt', 7), label: 'Priya Subagent' },
      goal: 'Collect Helios milestone evidence for the weekly delivery report.',
      action_label: 'Collecting milestone evidence',
      related: { type: 'project', id: id('prj', 2), label: 'Helios Health Website Revamp' },
      status: 'running',
      started_at: nowOffset(-12),
      ended_at: null,
      duration_ms: null,
      trigger: 'Priya Discord request',
      initiator: PRIYA,
      model_version: 'employee-sub.v1',
      cost_tokens: 900,
      approval_state: 'none',
      outcome_summary: 'Still running. Report is not ready.',
      inputs_summary: 'Helios tasks, overdue list, last report excerpt.',
      actions: [{ label: 'Read project work', result: 'In progress.' }],
      outputs: [],
      events: [
        { id: 'p1', at: nowOffset(-12), title: 'Queued from Discord', detail: 'Priya asked for evidence pack.', kind: 'system' },
        { id: 'p2', at: nowOffset(-9), title: 'Reading blockers', detail: 'Revision #4 dominates.', kind: 'action' },
      ],
      related_records: [
        { type: 'project', id: id('prj', 2), label: 'Helios Health Website Revamp' },
        { type: 'report', id: id('rpt', 2), label: 'Weekly delivery report' },
      ],
      failure: null,
      version: 2,
    },
    {
      id: id('run', 6),
      agent: { type: 'agent', id: id('agt', 6), label: 'Jordan Subagent' },
      goal: 'Remind Jordan that Vesper Hotels has no follow-up.',
      action_label: 'Nudged overdue follow-up',
      related: { type: 'lead', id: id('led', 1), label: 'Vesper Hotels' },
      status: 'succeeded',
      started_at: nowOffset(-6 * 60),
      ended_at: nowOffset(-6 * 60 + 2),
      duration_ms: 120000,
      trigger: 'Pipeline risk watch',
      initiator: { type: 'agent', id: id('agt', 1), label: 'CEO Agent' },
      model_version: 'employee-sub.v1',
      cost_tokens: 420,
      approval_state: 'none',
      outcome_summary: 'Discord nudge delivered to Jordan. Lead stage unchanged.',
      inputs_summary: 'Lead Vesper Hotels next_step_at overdue.',
      actions: [{ label: 'Send Discord nudge', result: 'Delivered to Jordan.' }],
      outputs: [{ label: 'Nudge', body: 'Vesper proposal has had no follow-up for 5 days.' }],
      events: [
        { id: 'n1', at: nowOffset(-6 * 60), title: 'Started', detail: 'Risk watch.', kind: 'system' },
        { id: 'n2', at: nowOffset(-6 * 60 + 2), title: 'Nudge sent', detail: 'Discord.', kind: 'result' },
      ],
      related_records: [
        { type: 'lead', id: id('led', 1), label: 'Vesper Hotels' },
        { type: 'employee', id: JORDAN.id, label: 'Jordan Hale' },
      ],
      failure: null,
      version: 1,
    },
    {
      id: id('run', 7),
      agent: { type: 'agent', id: id('agt', 2), label: 'Support Agent' },
      goal: 'Classify Helios HH-91 and route.',
      action_label: 'Classified escalation',
      related: { type: 'ticket', id: id('tkt', 2), label: 'HH-91' },
      status: 'succeeded',
      started_at: nowOffset(-6 * 60 + 2),
      ended_at: nowOffset(-6 * 60 + 5),
      duration_ms: 180000,
      trigger: 'Telegram intake',
      initiator: { type: 'agent', id: id('agt', 2), label: 'Support Agent' },
      model_version: 'support-intake.v6',
      cost_tokens: 1100,
      approval_state: 'none',
      outcome_summary: 'Tagged escalated. No client reply drafted in this run.',
      inputs_summary: 'Inbound Telegram from Naomi Wells.',
      actions: [{ label: 'Open ticket', result: 'HH-91 created and escalated.' }],
      outputs: [],
      events: [
        { id: 'c1', at: nowOffset(-6 * 60 + 2), title: 'Intake', detail: 'Telegram.', kind: 'system' },
        { id: 'c2', at: nowOffset(-6 * 60 + 5), title: 'Escalated', detail: 'Scope dispute.', kind: 'result' },
      ],
      related_records: [{ type: 'ticket', id: id('tkt', 2), label: 'HH-91' }],
      failure: null,
      version: 1,
    },
    {
      id: id('run', 8),
      agent: { type: 'agent', id: id('agt', 2), label: 'Support Agent' },
      goal: 'Queue a reply for NS-190 invoice coding.',
      action_label: 'Queued invoice draft',
      related: { type: 'ticket', id: id('tkt', 4), label: 'NS-190' },
      status: 'queued',
      started_at: nowOffset(-2),
      ended_at: null,
      duration_ms: null,
      trigger: 'Maya mention in desk',
      initiator: MAYA,
      model_version: 'support-reply.v4',
      cost_tokens: null,
      approval_state: 'none',
      outcome_summary: 'Queued behind NS-184. No draft yet.',
      inputs_summary: 'Ticket NS-190 billing question.',
      actions: [],
      outputs: [],
      events: [{ id: 'q1', at: nowOffset(-2), title: 'Queued', detail: 'Waiting for capacity.', kind: 'system' }],
      related_records: [{ type: 'ticket', id: id('tkt', 4), label: 'NS-190' }],
      failure: null,
      version: 1,
    },
  ]
}

export function createReports(): Report[] {
  return [
    {
      id: id('rpt', 1),
      title: 'Daily operations brief',
      type: 'daily_operations',
      status: 'ready',
      period_label: 'Saturday 12 Sep',
      generated_at: nowOffset(-22),
      author: { type: 'agent', id: id('agt', 1), label: 'CEO Agent' },
      scope: 'Northline Studio workspace',
      freshness: 'Source queues read 22 minutes ago',
      revision: 3,
      superseded_by: null,
      body: `Northline is in Attention, not At risk.

Human decisions that still sit with Maya:
1. Approve or edit the Northstar NS-184 latency reply. It is a draft. It has not been sent.
2. Decide Helios homepage revision #4: absorb or change-order. Priya cannot freeze content until this is called.

Delivery risk: Helios is At risk because of scope creep, not craft. Northstar needs attention because Sam is away and vendor logs are missing.

Desk risk: NS-184 still has SLA remaining if the draft is approved promptly. HH-91 is already breached and escalated.

Pipeline: Vesper Hotels proposal has had no follow-up for five days. Brightline Schools has no owner.

Capacity: Jordan is over capacity. Do not assign Atlas to Jordan without taking something off.

This brief is revision 3. Regenerating will create revision 4; it will not overwrite this document.`,
      linked_records: [
        { type: 'ticket', id: id('tkt', 1), label: 'NS-184' },
        { type: 'task', id: id('tsk', 1), label: 'Helios revision decision' },
        { type: 'lead', id: id('led', 1), label: 'Vesper Hotels' },
        { type: 'employee', id: JORDAN.id, label: 'Jordan Hale' },
      ],
      version: 3,
    },
    {
      id: id('rpt', 2),
      title: 'Weekly delivery report',
      type: 'weekly_delivery',
      status: 'generating',
      period_label: 'Week of 8 Sep',
      generated_at: null,
      author: { type: 'agent', id: id('agt', 7), label: 'Priya Subagent' },
      scope: 'Active projects',
      freshness: 'Generating from live project records',
      revision: 1,
      superseded_by: null,
      body: 'Generating. Priya Subagent is still collecting milestone evidence.',
      linked_records: [
        { type: 'project', id: id('prj', 2), label: 'Helios Health Website Revamp' },
        { type: 'agent_run', id: id('run', 5), label: 'Collecting milestone evidence' },
      ],
      version: 1,
    },
    {
      id: id('rpt', 3),
      title: 'Helios client health',
      type: 'client_health',
      status: 'ready',
      period_label: 'August',
      generated_at: nowOffset(-4 * 24 * 60),
      author: { type: 'agent', id: id('agt', 4), label: 'Helios Account Agent' },
      scope: 'Helios Health',
      freshness: 'Built from August tickets, tasks, and the signed SOW summary',
      revision: 2,
      superseded_by: null,
      body: `Helios remains a growth client with a real delivery strain.

Health is At risk because homepage revision #4 is outside signed scope. Design quality is not the issue.

Relationship: Naomi is engaged and still sending assets. Legal pages are slow on their side.

Recommendation: founder decision this week, then a calm written update. Do not let the account agent send a commercial email unaided.`,
      linked_records: [
        { type: 'client', id: HELIOS.id, label: 'Helios Health' },
        { type: 'project', id: id('prj', 2), label: 'Helios Health Website Revamp' },
      ],
      version: 2,
    },
    {
      id: id('rpt', 4),
      title: 'Pipeline review',
      type: 'pipeline_review',
      status: 'ready',
      period_label: 'September to date',
      generated_at: nowOffset(-2 * 24 * 60),
      author: { type: 'agent', id: id('agt', 1), label: 'CEO Agent' },
      scope: 'All open leads',
      freshness: 'Lead records as of two days ago',
      revision: 1,
      superseded_by: null,
      body: `Harbor Clinic is the only negotiation that is actually healthy.

Vesper Hotels is the leak: proposal sent, no follow-up. Brightline has no owner. Lumen Pay is still unqualified.

Atlas is not a lead — it is a client with a churn signal. Do not bury it in pipeline math.`,
      linked_records: [
        { type: 'lead', id: id('led', 1), label: 'Vesper Hotels' },
        { type: 'lead', id: id('led', 5), label: 'Harbor Clinic' },
        { type: 'client', id: ATLAS.id, label: 'Atlas Fintech' },
      ],
      version: 1,
    },
    {
      id: id('rpt', 5),
      title: 'Northstar project status',
      type: 'project_status',
      status: 'ready',
      period_label: 'Current sprint',
      generated_at: nowOffset(-9 * 60),
      author: MAYA,
      scope: 'Northstar Customer Portal',
      freshness: 'Manual founder note plus NS-184 thread',
      revision: 4,
      superseded_by: null,
      body: `Health is Needs attention, not At risk.

The portal is otherwise complete. The open issue is origin latency plus Sam’s unavailability. The client will stay steady if we send a dated plan today — the plan exists as a draft only.`,
      linked_records: [
        { type: 'project', id: id('prj', 1), label: 'Northstar Customer Portal' },
        { type: 'ticket', id: id('tkt', 1), label: 'NS-184' },
      ],
      version: 4,
    },
    {
      id: id('rpt', 6),
      title: 'Daily operations brief',
      type: 'daily_operations',
      status: 'superseded',
      period_label: 'Friday 11 Sep',
      generated_at: nowOffset(-26 * 60),
      author: { type: 'agent', id: id('agt', 1), label: 'CEO Agent' },
      scope: 'Northline Studio workspace',
      freshness: 'Superseded by Saturday revision 3',
      revision: 2,
      superseded_by: id('rpt', 1),
      body: 'Friday brief. Kept for history. Saturday revision 3 is current.',
      linked_records: [],
      version: 2,
    },
  ]
}

export function createNotifications(): NotificationItem[] {
  return [
    {
      id: id('ntf', 1),
      kind: 'approval',
      title: 'Approve NS-184 send',
      body: 'Support Agent drafted a Telegram reply. It is not sent.',
      related: { type: 'approval', id: id('apr', 1), label: 'Send NS-184 reply' },
      occurred_at: nowOffset(-8),
      read: false,
    },
    {
      id: id('ntf', 2),
      kind: 'approval',
      title: 'Helios change order',
      body: 'Homepage revision #4 needs absorb vs change-order.',
      related: { type: 'approval', id: id('apr', 2), label: 'Issue Helios change order' },
      occurred_at: nowOffset(-40),
      read: false,
    },
    {
      id: id('ntf', 3),
      kind: 'sla',
      title: 'NS-184 SLA still open',
      body: 'Strategic incident. Draft exists; delivery has not happened.',
      related: { type: 'ticket', id: id('tkt', 1), label: 'NS-184' },
      occurred_at: nowOffset(-15),
      read: false,
    },
    {
      id: id('ntf', 4),
      kind: 'failed_run',
      title: 'Meridian CRM write failed',
      body: 'Required field next_touch_at missing. Retry eligible.',
      related: { type: 'agent_run', id: id('run', 3), label: 'Meridian CRM update' },
      occurred_at: nowOffset(-93),
      read: false,
    },
    {
      id: id('ntf', 5),
      kind: 'blocked',
      title: 'Helios delivery blocked',
      body: 'Content freeze cannot move without a founder decision.',
      related: { type: 'task', id: id('tsk', 1), label: 'Helios revision decision' },
      occurred_at: nowOffset(-40),
      read: false,
    },
    {
      id: id('ntf', 6),
      kind: 'follow_up',
      title: 'Vesper follow-up overdue',
      body: 'Proposal sent five days ago. No next conversation.',
      related: { type: 'lead', id: id('led', 1), label: 'Vesper Hotels' },
      occurred_at: nowOffset(-5 * 24 * 60),
      read: false,
    },
  ]
}
